### 

@base_url = http://127.0.0.1:5000


### 1. Post new user

POST {{base_url}}/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "email": "nguyenmanhtriet1@gmail.com",
  "fullName": "Nguyen Manh Triet",
  "password": "12345678",
  "username": "NguyenCoderVN1"
}


### 1. followUnfollower

POST {{base_url}}/api/users/follow/69ffdba6aeb2945641fd3c17 HTTP/1.1
Content-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}

{}


### 

# @name login

POST http://127.0.0.1:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "password": "12345678",
  "username": "NguyenCoderVN"
}


### 

# @name getMe

GET http://127.0.0.1:5000/api/auth/me HTTP/1.1
Cookie: jwt={{login.response.cookies.jwt.value}}


### getUserProfile

GET http://127.0.0.1:5000/api/users/profile/NguyenCoderVN1 HTTP/1.1
Cookie: jwt={{login.response.cookies.jwt.value}}


### getSuggestedUsers

GET http://127.0.0.1:5000/api/users/suggested HTTP/1.1
Cookie: jwt={{login.response.cookies.jwt.value}}


### Update user

POST {{base_url}}/api/users/update HTTP/1.1
Crntent-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}

{
  "email": "nguyenmanhtriet3@gmail.com",
  "username": "NguyenCoderVN"
}


### Post

POST {{base_url}}/api/posts/create HTTP/1.1
Content-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}

{
  "text": "test02"
}


### Delete post

POST {{base_url}}/api/posts/delete/6a0127b6786013f23c8343ca HTTP/1.1
Content-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}


### Comment on post

POST {{base_url}}/api/posts/comment/6a012dfef6ef1f0f7caf00df HTTP/1.1
Content-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}

{
  "text": "comment"
}


### Like on post

POST {{base_url}}/api/posts/like/6a012dfef6ef1f0f7caf00df HTTP/1.1
Content-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}

{}


### GET ALL POSTS

GET {{base_url}}/api/posts/all HTTP/1.1
Cookie: jwt={{login.response.cookies.jwt.value}}
