### 

@base_url = http://localhost:5000/api
@contentType = application/json

# @name login

POST {{base_url}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
  "password": "password123",
  "username": "testuser8"
}


### 

@myUsername = {{login.response.body.data.username}}
@token = {{login.response.cookies.jwt.value}}


### 

GET {{base_url}}/users/profile/{{myUsername}} HTTP/1.1
Cookie: jwt={{token}}


### 

# @name getSuggested

GET {{base_url}}/users/suggested HTTP/1.1
Cookie: jwt={{token}}


### 

@targetUserId = {{getSuggested.response.body.data[0]._id}}


### 

# @name updateUser

POST {{base_url}}/users/update HTTP/1.1
Content-Type: {{contentType}}
Cookie: jwt={{token}}

{
  "bio": "Học lập trình tại Ho Chi Minh City 🚀",
  "link": "https://github.com/nguyencodervn"
}


### 

# @name toggleFollow

POST {{base_url}}/users/follow/{{targetUserId}} HTTP/1.1
Cookie: jwt={{token}}
