### 

@base_url = http://127.0.0.1:5000


### POST Login

# @name login

POST {{base_url}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "password": "12345678",
  "username": "test1"
}


### GET Profile by username

GET {{base_url}}/api/users/profile/test1 HTTP/1.1
Cookie: jwt={{login.response.cookies.jwt.value}}


### POST Update user

POST {{base_url}}/api/users/update HTTP/1.1
Content-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}

{
  "username": "test3"
}


### 6a019180bcd4b9901fc7ae50 test1 id


### 6a0191a5bcd4b9901fc7ae51 test2 id


### 6a0191aabcd4b9901fc7ae52 test3 id


### POST follow userId

POST {{base_url}}/api/users/follow/6a0191a5bcd4b9901fc7ae51 HTTP/1.1
Content-Type: application/json
Cookie: jwt={{login.response.cookies.jwt.value}}

{}


### GET suggested followers

GET http://127.0.0.1:5000/api/users/suggested HTTP/1.1
Cookie: jwt={{login.response.cookies.jwt.value}}
